import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import javax.swing.JFileChooser

private val EditedBackground = Color(0xFFFFF59D)

fun main() = application {
    Window(onCloseRequest = ::exitApplication, title = "공휴일 데이터 검수 도구") {
        MaterialTheme {
            App()
        }
    }
}

@Composable
fun App() {
    var countries by remember { mutableStateOf<CountryList?>(null) }
    var countriesError by remember { mutableStateOf<String?>(null) }
    var selectedCountry by remember { mutableStateOf<String?>(null) }
    var status by remember { mutableStateOf("국가 목록을 불러오는 중...") }
    var busy by remember { mutableStateOf(false) }

    var generated by remember { mutableStateOf(false) }
    var years by remember { mutableStateOf<List<YearGroup>>(emptyList()) }
    var appleError by remember { mutableStateOf<String?>(null) }

    val scope = rememberCoroutineScope()

    fun sourceOf(code: String) = if (countries?.nager?.contains(code) == true) "Nager" else "Google"

    // 최초 1회: update_holidays.py에서 국가 목록을 직접 읽어온다(Kotlin에 따로 안 둠).
    LaunchedEffect(Unit) {
        withContext(Dispatchers.IO) {
            Pipeline.countryList()
        }.onSuccess {
            countries = it
            status = "국가를 선택하세요 (저장소: ${Pipeline.repoRoot})"
        }.onFailure {
            countriesError = it.message
            status = "❌ 국가 목록을 못 읽었습니다"
        }
    }

    fun runGenerate(code: String) {
        busy = true
        generated = false
        years = emptyList()
        appleError = null
        status = "$code 서버에서 생성 중 (update_holidays.py)..."
        scope.launch {
            val regenResult = withContext(Dispatchers.IO) { Pipeline.regenerate(code) }
            if (regenResult.isFailure) {
                status = "❌ ${regenResult.exceptionOrNull()?.message}"
                busy = false
                return@launch
            }
            status = "$code 생성된 데이터 읽는 중..."
            val ourData = withContext(Dispatchers.IO) { Pipeline.readHolidayList(code) }
            if (ourData.isFailure) {
                status = "❌ ${ourData.exceptionOrNull()?.message}"
                busy = false
                return@launch
            }
            val file = ourData.getOrThrow()
            years = file.holidays.toSortedMap().map { (year, entries) -> YearGroup(year, entries) }
            generated = true
            status = "✅ 생성 완료 (${years.size}개 연도) — 연도를 펼쳐 수정하거나, 애플 대조/내보내기를 진행하세요"
            busy = false
        }
    }

    fun runAppleCompare() {
        val code = selectedCountry ?: return
        busy = true
        appleError = null
        status = "$code 애플 iCloud ICS 가져오는 중..."
        scope.launch {
            val apple = withContext(Dispatchers.IO) { AppleIcs.fetch(code) }
            if (apple.error != null) {
                appleError = apple.error
                status = "⚠️ 애플 ICS 실패 — 대조를 진행하지 못했습니다"
                busy = false
                return@launch
            }
            for (group in years) {
                val appleForYear = apple.byYear[group.year]
                if (appleForYear == null) {
                    group.appleStatus = AppleYearStatus.UNSUPPORTED
                    group.appleDiffs = emptyMap()
                    continue
                }
                val ourByDate = group.holidays.groupBy({ it.date }, { it.name })
                    .mapValues { it.value.toSet() }
                val allDates = appleForYear.keys + ourByDate.keys
                val diffs = mutableMapOf<String, Set<String>>()
                for (date in allDates) {
                    val a = appleForYear[date] ?: emptySet()
                    val o = ourByDate[date] ?: emptySet()
                    if (a != o) diffs[date] = a
                }
                group.appleDiffs = diffs
                group.appleStatus = AppleYearStatus.CHECKED
            }
            status = "✅ 애플 대조 완료"
            busy = false
        }
    }

    fun exportJson() {
        val code = selectedCountry ?: return
        val chooser = JFileChooser().apply {
            dialogTitle = "내보내기"
            selectedFile = File(Pipeline.repoRoot, "holiday_list_${code}_reviewed.json")
        }
        if (chooser.showSaveDialog(null) != JFileChooser.APPROVE_OPTION) return
        val holidaysMap = years.associate { group ->
            group.year to group.holidays.map { HolidayEntry(it.date, it.name) }
        }
        chooser.selectedFile.writeText(formatHolidayFile(code, holidaysMap))
        status = "✅ 내보내기 완료: ${chooser.selectedFile.name}"
    }

    Column(Modifier.fillMaxSize().padding(16.dp)) {
        Text("공휴일 데이터 검수 도구", style = MaterialTheme.typography.headlineSmall)
        Spacer(Modifier.height(4.dp))
        Text(
            "국가 선택 → 생성(실제 파이프라인 재사용) → 연도를 펼쳐 이름 직접 수정 → " +
                "애플과 대조(참고용, 비공식) → 내보내기(JSON)",
            style = MaterialTheme.typography.bodySmall,
        )
        Spacer(Modifier.height(12.dp))

        Row(verticalAlignment = Alignment.CenterVertically) {
            countriesError?.let {
                Text("❌ 국가 목록 오류: $it", color = MaterialTheme.colorScheme.error)
            } ?: run {
                val allCodes = ((countries?.nager ?: emptyList()) + (countries?.google ?: emptyList())).sorted()
                var expanded by remember { mutableStateOf(false) }
                Box {
                    OutlinedButton(onClick = { expanded = true }, enabled = !busy) {
                        Text(
                            selectedCountry?.let { countryDisplayName(it, sourceOf(it)) } ?: "국가 선택"
                        )
                    }
                    DropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
                        allCodes.forEach { code ->
                            val source = sourceOf(code)
                            DropdownMenuItem(
                                text = { Text(countryDisplayName(code, source)) },
                                onClick = {
                                    selectedCountry = code
                                    generated = false
                                    years = emptyList()
                                    appleError = null
                                    status = "${countryDisplayName(code, source)} 선택됨 — '생성' 버튼을 눌러주세요"
                                    expanded = false
                                },
                            )
                        }
                    }
                }
                Spacer(Modifier.width(8.dp))
                Button(
                    onClick = { selectedCountry?.let { runGenerate(it) } },
                    enabled = !busy && selectedCountry != null,
                ) { Text("생성") }
                Spacer(Modifier.width(8.dp))
                Button(
                    onClick = { runAppleCompare() },
                    enabled = !busy && generated,
                ) { Text("애플과 대조하기") }
                Spacer(Modifier.width(8.dp))
                Button(
                    onClick = { exportJson() },
                    enabled = !busy && generated,
                ) { Text("내보내기") }
            }
        }

        Spacer(Modifier.height(8.dp))
        Text(status, style = MaterialTheme.typography.bodyMedium)
        appleError?.let {
            Text(
                "⚠️⚠️⚠️ 애플 ICS 실패(URL이 막혔거나 형식이 바뀌었을 수 있음): $it",
                color = MaterialTheme.colorScheme.error,
                modifier = Modifier.background(Color(0xFFFFF3CD)).padding(8.dp),
            )
        }
        Spacer(Modifier.height(12.dp))

        if (years.isNotEmpty()) {
            LazyColumn(Modifier.weight(1f).fillMaxWidth()) {
                items(years, key = { it.year }) { group ->
                    YearGroupView(group)
                }
            }
        } else {
            Box(Modifier.weight(1f).fillMaxWidth().verticalScroll(rememberScrollState())) {
                Text(
                    "국가를 고르고 '생성'을 누르면 실제 파이프라인(update_holidays.py)으로 재생성한 뒤\n" +
                        "연도별로 묶어서 보여줍니다. 연도의 +/-를 눌러 펼치면 날짜/이름이 나오고,\n" +
                        "이름은 바로 수정할 수 있습니다. 수정한 항목은 배경색이 바뀝니다.\n\n" +
                        "'애플과 대조하기'를 누르면 애플 iCloud ICS(참고용, 비공식)와 날짜 단위로 비교해서,\n" +
                        "애플이 지원하지 않는 연도는 '애플 데이터 없음'으로 표시하고, 지원하는 연도 중\n" +
                        "애플과 다른 날짜만 표시합니다.\n\n" +
                        "'내보내기'를 누르면 지금까지의 내용을 JSON 파일로 저장합니다.",
                    style = MaterialTheme.typography.bodyMedium,
                )
            }
        }
    }
}

@Composable
fun YearGroupView(group: YearGroup) {
    Column {
        Row(
            Modifier
                .fillMaxWidth()
                .background(if (group.isEdited) EditedBackground else Color.Transparent)
                .clickable { group.expanded = !group.expanded }
                .padding(8.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(if (group.expanded) "−" else "+", Modifier.width(24.dp), style = MaterialTheme.typography.titleMedium)
            Text(
                "${group.year}년 (${group.holidays.size}건)",
                Modifier.weight(1f),
                style = MaterialTheme.typography.titleSmall,
            )
            when (group.appleStatus) {
                AppleYearStatus.UNSUPPORTED -> Text(
                    "애플 데이터 없음",
                    color = Color.Gray,
                    style = MaterialTheme.typography.labelSmall,
                )
                AppleYearStatus.CHECKED -> if (group.appleDiffs.isNotEmpty()) {
                    Text(
                        "⚠ 애플과 ${group.appleDiffs.size}건 다름",
                        color = MaterialTheme.colorScheme.error,
                        style = MaterialTheme.typography.labelSmall,
                    )
                } else {
                    Text("✅ 애플과 일치", color = Color(0xFF2E7D32), style = MaterialTheme.typography.labelSmall)
                }
                AppleYearStatus.NOT_CHECKED -> {}
            }
        }
        if (group.expanded) {
            group.holidays.forEach { holiday ->
                HolidayRowView(holiday, group)
            }
        }
    }
}

@Composable
fun HolidayRowView(holiday: EditableHoliday, group: YearGroup) {
    val appleNamesForDate = group.appleDiffs[holiday.date]
    Row(
        Modifier
            .fillMaxWidth()
            .background(if (holiday.edited) EditedBackground else Color.Transparent)
            .padding(start = 32.dp, top = 4.dp, bottom = 4.dp, end = 8.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(holiday.date, Modifier.width(80.dp), style = MaterialTheme.typography.bodySmall)
        Column(Modifier.weight(1f)) {
            BasicTextField(
                value = holiday.name,
                onValueChange = {
                    holiday.name = it
                    holiday.edited = true
                },
                textStyle = MaterialTheme.typography.bodyMedium.copy(color = MaterialTheme.colorScheme.onSurface),
                singleLine = true,
                modifier = Modifier
                    .fillMaxWidth()
                    .border(1.dp, Color(0xFFE0E0E0))
                    .padding(4.dp),
            )
            appleNamesForDate?.let {
                Text(
                    "애플: ${it.ifEmpty { setOf("(없음)") }.joinToString(", ")}",
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.error,
                )
            }
        }
    }
}
